### ISSUE TITLE
Mac OS can't install with package manager or manifest file on Unity 2022.3.13f1 

### ISSUE THREAD

**Issue by Saurabh7SSR** [rive-app/rive-unity#1]
An error occurred while resolving packages:
  Project has invalid dependencies:
    app.rive.rive-unity: Error when executing git command. Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by Saurabh7SSR** [comment]
Drag and drop works but not above methods.

**Comment by luigi-rosso** [comment]
Sounds like something might be configured incorrectly with git on your system, the repository is public. Make sure you're pointing to the latest version (currently v0.1.16):

```
{
  "dependencies": {
    "app.rive.rive-unity": "git@github.com:rive-app/rive-unity.git?path=package#v0.1.16",
  }
}
```

If that still doesn't work, you can download a [zip of the package](https://github.com/rive-app/rive-unity/archive/refs/tags/v0.1.16.zip) and install it via "add package from disk".

**Comment by Saurabh7SSR** [comment]
Thanks, retried installing zip of the package  using Unity package manager and it worked, I was trying to add zip archive directly before, this time I extracted and added the package.json file, it worked like a charm. 

git install still not working though, other git packages install without any problems.

**Comment by BitBarrel** [comment]
> Please make sure you have the correct access rights
> and the repository exists.

Same problem with the same git error message on Windows.

**Comment by Saurabh7SSR** [comment]
@HayesGordon solved this.

Can you try adding the rive package from the HTTP URL instead:
https://github.com/rive-app/rive-unity.git?path=package#v0.1.29

Package installed with HTTP URL, I was entering URL into "add package by name" so it was't working before. Thanks.
