### ISSUE TITLE
Console Platform Support and Timelines

### ISSUE THREAD

**Issue by jay8ee** [rive-app/rive-unity#15]
Do you have plans to add support for the various console platforms that Unity currently supports? If so I would love to get an idea of the timeline/roadmap for this.

**Comment by luigi-rosso** [comment]
We do, we're working on getting access to dev kits right now but are also looking for partners  to work with who can help accelerate that work if they already have access to dev kits.

We're also working on open-sourcing the entire plugin so users can self-serve when necessary! We should have more news on both these fronts in January, but no specific date on expected console support yet.

**Comment by jay8ee** [comment]
Thanks for the info, looking forward to hearing more.
