### ISSUE TITLE
Foreground Image format only png supported 

### ISSUE THREAD

**Issue by Saurabh7SSR** [rive-app/rive-unity#16]
Foreground image i.e. image "bring to front" on top of already having a background image is invisible if jpg or webp or psd only png is visible. I tested the same on ios rive renderer runtime and it doesn't have the issue. So it seems to be an issue with unity rive renderer.

**Comment by HayesGordon** [comment]
Hi @Saurabh7SSR, at this time only PNG is supported for Unity. Apologies for this, I thought there was an info banner in our docs that stated this, but I see there isn't. We're looking into supporting the other formats, hopefully soon.

**Comment by Saurabh7SSR** [comment]
No Problem. Thanks for confirming.

**Comment by damzobridge** [comment]
JPEG is now supported from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188) upwards. Please upgrade and let us know if you run into issues.
