### ISSUE TITLE
Issues when trying to run Rive Unity Examples

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#17]
Hi,

I’m trying to run Rive Unity Examples provided at: [GitHub - rive-app/rive-unity-examples: A collection of examples using Rive Unity](https://github.com/rive-app/rive-unity-examples) , but I am having some issues. Here are the steps that I followed:

1. I cloned the Rive Unity Examples Repo

2. I chose “Add Project from Disk” option in Unity Hub and added the getting-started example that is in the Repo

![image](https://github.com/rive-app/rive-unity/assets/20733892/fe4f1556-49de-45fb-a989-e7b516f230b0)
![image](https://github.com/rive-app/rive-unity/assets/20733892/c23edce2-7c47-474b-bf21-4209e3678e98)

3. As soon as I opened the project in Unity Hub, I got an error to which I responded by selecting “Enter Safe Mode”

![image](https://github.com/rive-app/rive-unity/assets/20733892/407be58e-ade9-4ebd-a302-c1ee452dc508)

4. I opened Windows → Package Manager 
![image](https://github.com/rive-app/rive-unity/assets/20733892/5b387cbc-0309-4373-aa45-ebd3000115f8)

5. I chose to install the Rive Unity Package upon which I am running into errors shown in the snapshots
![image](https://github.com/rive-app/rive-unity/assets/20733892/7cdd1e9c-d366-4b52-adbd-832b1a54a953)
![image](https://github.com/rive-app/rive-unity/assets/20733892/17991383-c5da-453d-a055-169545c9f2d6)

One of the errors is posted below:

[Package Manager Window] Error adding package: [git@github.com](mailto:git@github.com):rive-app/rive-unity.git?path=package#v0.1.30.
Unable to add package [git@github.com:rive-app/rive-unity.git?path=package#v0.1.30]:
  Error when executing git command. fatal: not in a git directory
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
UnityEditor.PackageManager.UI.Internal.UpmBaseOperation1<UnityEditor.PackageManager.Requests.AddRequest>:OnError (UnityEditor.PackageManager.UI.Internal.UIError) UnityEditor.PackageManager.UI.Internal.UpmBaseOperation1<UnityEditor.PackageManager.Requests.AddRequest>:Progress ()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
[Editor.log](https://github.com/rive-app/rive-unity/files/13970490/Editor.log)

I've also attached Editor.log file

How can I resolve these?

Thank you.

**Comment by HayesGordon** [comment]
Hi @trdroid, I believe it's because the Rive package is being added through git ssh for this sample, which you may not have set up.

I'll make a PR to switch this to instead download the package through HTTP to fix this.

You should be able to fix this by opening the project (ignore the safe mode), and then add the Rive package yourself using the HTTP url, see here: https://help.rive.app/game-runtimes/unity/getting-started#installation

**Comment by trdroid** [comment]
Hi @HayesGordon, did you mean for me to try after you switch to make the package available through HTTP?

Because I just tried with the HTTPS URL and I am getting the following error:
![image](https://github.com/rive-app/rive-unity/assets/20733892/28876245-771a-47be-bdf7-e5a5885fdc26)

BTW, this is not really a blocker, as I am able to get it to work by cloning the repo and using the "Add package from disk..." option.

**Comment by HayesGordon** [comment]
I updated the samples to use HTTP. Could you try and pull the latest @trdroid ?

But it's strange that you're seeing this when editing it yourself. Let's keep the issue open to see if others encounter the same or if it's something potentially just with your environment.

**Comment by trdroid** [comment]
@HayesGordon, thank you for a prompt fix! I cloned the Rive Unity Examples repo. and opened the getting-started project and this time I am able to add The Rive Unity Runtime using the HTTPS option, the snapshot of which can be seen below:

![image](https://github.com/rive-app/rive-unity/assets/20733892/3845fbd6-2b48-4c67-ae2a-d53746de658a)

**Comment by HayesGordon** [comment]
Awesome! I'll go ahead and close this issue then. Thanks for confirming it worked.
