### ISSUE TITLE
unity2020.3 Unable to add package [git@github.com:rive-app/rive-unity.git?path=package#v0.1.10]

### ISSUE THREAD

**Issue by AzkabanPresident** [rive-app/rive-unity#2]
[Package Manager Window] Unable to add package [git@github.com:rive-app/rive-unity.git?path=package#v0.1.10]:
  Version range 'github.com:rive-app/rive-unity.git?path=package#v0.1.10' is invalid.

**Comment by luigi-rosso** [comment]
Try the latest version [v0.1.16](https://github.com/rive-app/rive-unity/releases/tag/v0.1.16). We need to update the README!

```
{
  "dependencies": {
    "app.rive.rive-unity": "git@github.com:rive-app/rive-unity.git?path=package#v0.1.16",
  }
}
```

**Comment by BitBarrel** [comment]
The latest version can be found here:

https://github.com/rive-app/rive-unity/tags
