### ISSUE TITLE
Various iOS build errors

### ISSUE THREAD

**Issue by tomkail** [rive-app/rive-unity#20]
Can't say much about these, but they prevent us building our project to iOS.
<img width="276" alt="image" src="https://github.com/rive-app/rive-unity/assets/1252816/4813243a-879d-4429-b181-040e88b0ac60">

**Comment by luigi-rosso** [comment]
Thanks for reporting, we're looking into it.

**Comment by luigi-rosso** [comment]
What version of Unity are you using and what iOS version are you targeting (you can find it under Build Settings):
<img width="631" alt="CleanShot 2024-02-14 at 15 53 55@2x" src="https://github.com/rive-app/rive-unity/assets/454182/080dccb8-c54f-4d06-b933-f7fe17b95f75">

Do you see a "rive.a" in your project file:
![CleanShot 2024-02-14 at 16 03 26@2x](https://github.com/rive-app/rive-unity/assets/454182/3b7f6824-48ee-4159-93c1-3ad5c1fbe6a7)


I do get a linker error with the current version, but it's only for makeRiveRendererMetal (we broke some build scripts which I'm fixing right now). I'll ping you to try again with the new build, but I suspect something else is going on in your case as all the symbols seem to be undefined.

Here is an example running on the latest version (building now):
![IMG_4410](https://github.com/rive-app/rive-unity/assets/454182/e52c5c3e-975b-49bb-aa54-0ac556bc0fff)

**Comment by luigi-rosso** [comment]
Can you give [v0.1.70](https://github.com/rive-app/rive-unity/releases/tag/v0.1.70) a try and report with any further errors?

**Comment by Adeptus-Astartes** [comment]
Tried 0.1.87 - works fine on iOS
