### ISSUE TITLE
RiveNative: Unsuported GPU. Rive currently requires rasterizer order views.

### ISSUE THREAD

**Issue by marcolatellafrias** [rive-app/rive-unity#21]
When opening any of the example projects, i get this error, the scene in the project is just blank, as shown in the image. Is this because of my gpu? is there a workaround? Thank you

![image](https://github.com/rive-app/rive-unity/assets/52115956/b7a7c2e4-be75-4c3f-ab46-3850f9ad783c)

**Comment by marcolatellafrias** [comment]
The error stopped showing in console when i changed from gamma to linear, but the scene is still empty, when i run the project it just stays blank, and when i click on a rive file, it crashes.

![image](https://github.com/rive-app/rive-unity/assets/52115956/ad78d3f2-32a2-44ec-9d28-39956ac75fce)

![image](https://github.com/rive-app/rive-unity/assets/52115956/37b0c83a-d191-4eb9-b982-e6d7301f5b42)

**Comment by luigi-rosso** [comment]
Rive currently requires Rasterizer Order Views in D3D11, although we're removing that requirement shortly and Rive will work on all GPUs. It seems like your GPU is currently not compatible and it looks like we're not doing a good job of capturing that incompatibility in OpenGL (the crash in your last screenshot).

What is the GPU on your machine? 

I'll post in here as soon as the more general GPU support lands (should be any day).

**Comment by marcolatellafrias** [comment]
Hey luigi, thanks for your reply, i have an AMD radeon r7 200. Is there a list of supported gpus? maybe if i just buy a compatible one, i can solve it faster

**Comment by marcolatellafrias** [comment]
Thank you! now it works properly

**Comment by luigi-rosso** [comment]
Excellent, thanks for confirming! I'll close the issue now.
