### ISSUE TITLE
[Android][IL2CPP][Mono] Not working on Runtime

### ISSUE THREAD

**Issue by Adeptus-Astartes** [rive-app/rive-unity#23]
Hi there
I just checked this plugins 0.1.87 - its Awesome!

Works fine on IOS, however on Android at Runtime it throws 
`DllNotFoundException: Unable to load DLL 'rive'. Tried the load the following dynamic libraries: Unable to load dynamic library 'rive' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "rive" not found
03-04 16:10:40.038 26220 26285 E Unity   :   at Rive.RenderQueue.unrefRenderQueue (System.IntPtr renderQueue) [0x00000] in <00000000000000000000000000000000>:0 
03-04 16:10:40.038 26220 26285 E Unity   :   at Rive.RenderQueue.Finalize () [0x00000] in <00000000000000000000000000000000>:0 `

Samsung S21 (Exynos)

I tried multiple compilation options, but it doesn't help. Looking for help

**Comment by Adeptus-Astartes** [comment]
I see that librive.so is presented 
<img width="357" alt="image" src="https://github.com/rive-app/rive-unity/assets/70582099/7961167f-0439-40fa-85eb-3a6530b89c26">

**Comment by Adeptus-Astartes** [comment]
@luigi-rosso  Hi, could you please check those issue

**Comment by damzobridge** [comment]
This should be fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188)! Let us know if you still run into any issues with Android not working properly.
