### ISSUE TITLE
[MacOS] "Function FD is using language version 3.1 which is incompatible with this OS"

### ISSUE THREAD

**Issue by Mattish** [rive-app/rive-unity#24]
rive-unity Version: v0.1.93
MacOS Version: Ventura 13.6
Mac Mini M1
Xcode Version: 14.3
Unity Version: 2022.3.19f1

Attempting a CLI Unity build shows the final message when attempting to import the .riv file:

`Start importing <filename.riv> using Guid(...) Importer(-1,00000000000000000000000000000000) Function FD is using language version 3.1 which is incompatible with this OS.`

After this the CI build process immediately ends.

Via the Unity Editor GUI on the same machine, attempting to re-import the .riv file in the editor causes Unity to immediately close without any crash report triggered.

This project is successfully building and working on another more recent macOS device.

Is there an Xcode or other OS requirement to use rive-unity on MacOS? I am unable to find any requirements beyond being on an Apple Sillicon(M1 etc.) device.

**Comment by davidkaplan** [comment]
Same issue here when building a Unity project with .riv assets:
`Start importing Assets/<my asset>.riv using Guid(d4bfe7520d5b54825a71b3f38d72e9d0) Importer(-1,00000000000000000000000000000000) Function HD has a deployment target (0x00020006) which is incompatible with this OS (0x00020005).`
and
`Function GD has a deployment target (0x00020006) which is incompatible with this OS (0x00020005).`
Currently running macOS Ventura 13.2.1.

**Comment by damzobridge** [comment]
We're currently looking into this. Right now, the plugin supports MacOS 14 (Sonoma) upwards, but we're working on an update that should add support for MacOS 13 (Ventura).

**Comment by damzobridge** [comment]
This should now be fixed on version [v0.1.233](https://github.com/rive-app/rive-unity/releases/tag/v0.1.233). Please let us know if that isn't the case for you @davidkaplan
