### ISSUE TITLE
Gradients cause banding in SRP and Direct3D11

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#35]
Gradients in a riv file cause banding when using SRP and Direct3D11. 

![image](https://github.com/rive-app/rive-unity/assets/11244755/faeaca85-131a-406e-824f-e92608568913)

Use this riv file with the repo below:
[banding.zip](https://github.com/rive-app/rive-unity/files/14911881/banding.zip)

https://github.com/rive-app/rive-unity/files/14911845/URPOffsetIssue.zip

**Comment by JadenH** [comment]
I'm also having this issue, and found a discussion on Discord with others having this issue: https://discord.com/channels/532365473602600965/1215855416043503627

I also linked the Discord thread back to this issue. Fixing this issue would help at least four Unity developers using the Rive Unity runtime!

**Comment by JadenH** [comment]
This looks related: https://rive.app/community/forums/bugs/fsLjspgTHYcR/transparency-issues-in-ue5/ftjRTvjFapi8

It looks like this was fixed in UE5/DX11! Given both runtimes use DX11, it feels plausible that the fix for UE5/DX11 runtime can probably fix Unity/DX11 runtime. :)

**Comment by JadenH** [comment]
Also refer to: https://github.com/rive-app/rive-unreal/issues/55

**Comment by damzobridge** [comment]
Hi Jaden, thanks for detailing the issue. We're looking into a fix for this in Unity.

**Comment by damzobridge** [comment]
This should be fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188). Please upgrade and let us know if you're still running into issues with banding.
