### ISSUE TITLE
Artboard resize on timeline not updated at runtime

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#38]
When an artboard is resized via a timeline, the new artboard size is not accessible at runtime.

This functionality is needed for UI re-arrangement for different aspect ratio screens.

To reproduce with the repo below:

Open the artboard_bug.rev file (in Assets folder) in the Rive editor. 
Play the state machine. 
Change the aspect ratio input value. The change-over point is 0.6
Notice how the artboard size changes and the square is re-positioned.
Open the Unity project.
Open the Artboard bug scene.
Press Play. 
Resize the Game window. 
Notice how the square is re-positioned but the arboard size stays the same.
Doing a re-init on the artboard-related code doesn't help.
The aspect ratio input is set in the SetDisplay.cs script.

Repo:
[Artboard bug.zip](https://github.com/rive-app/rive-unity/files/14926797/Artboard.bug.zip)

**Comment by damzobridge** [comment]
Not sure if we currently allow artboard-resizing via a timeline at runtime, but we do support setting an artboard's width and height in Unity from [v0.2.1](https://github.com/rive-app/rive-unity/releases/tag/v0.2.1). 

So you should be able to implement something like this with events.
