### ISSUE TITLE
Package from disk wrong version

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#4]
When installing the package from disk, it shows version 1.0.0 in the package manager instead of version 0.1.16
Package used:
https://github.com/rive-app/rive-unity/archive/refs/tags/v0.1.16.zip

**Comment by luigi-rosso** [comment]
Ah good point, we don't sync the version in the package.json. We'll get that in!

**Comment by luigi-rosso** [comment]
This should be fixed as of version [v0.1.22](https://github.com/rive-app/rive-unity/releases/tag/v0.1.22)
