### ISSUE TITLE
The ProceuduralRenderingScene does not draw any procedural shapes

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#40]
When I try to run the scene "ProceuduralRenderingScene .unity" in the Unity Editor, I just see a Cube rotating, but the procedural shapes are not drawn on it

![image](https://github.com/rive-app/rive-unity/assets/20733892/d7074b19-ac1a-43c6-ae49-67268a532847)

But this is the expected output:

![image](https://github.com/rive-app/rive-unity/assets/20733892/e44fe813-507f-4242-b57a-a88a1d367459)

**Comment by damzobridge** [comment]
Thanks for bringing this up. This issue should be fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188) upwards.
