### ISSUE TITLE
URP does not work for Metal

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#41]
Try to open and run the minion URP project on Mac, using Metal. It doesn't work.

**Comment by damzobridge** [comment]
Are you still having this issue? I've not been able to reproduce this with the minions URP project on my end on a Mac with metal. 

Do you have a repro project we could test?

**Comment by BitBarrel** [comment]
I have switched my project back to the build-in pipeline because at the time, there were too many issues with it, so I cannot test it anymore. It is possible that our issue was related to drawing directly to the screen (similar to RiveScreen.cs) but that seems to be difficult if not impossible to do with URP.
