### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by pshtif** [rive-app/rive-unity#42]
Just honest question as I downloaded the latest 0.1.112 tag and latest examples, tried to run it on Windows in Unity 2022.3.24f1 and none of the examples render anything. I've tried to set various graphics apis and various build targets but none of them worked. So I am just asking if it is even feasible for testing right now or should we postpone it till its more stable/viable.

**Comment by BitBarrel** [comment]
It works for me and from my experience, it is good enough to start using it. The best way I find to get it to work is to do this:

-Use the project in examples/basic.
-Open the project using Unity Editor 2023.1.17f1
-Initially stay away from URP. Use the project setup (build-in pipeline).
-Try to build on windows and Android, it should work.

I use Rive tag version 0.1.108 so maybe try that one if it still doesn't work.

As for URP, first start with opening the minion project using the aforementioned Unity version and tag:
https://github.com/rive-app/rive-unity-examples

Setting up an URP project from scratch requires a careful setup and Rive script API usage and settings so it's best to start with a working minion project and go from there.

0.1.108

**Comment by pshtif** [comment]
You lost me at the Unity Editor version, the 2023 version is completely useless due to various reasons. We also have multiple live projects with hundreds of people on various Unity versions if I want to use a technology professionally it should work on all of those. 

So let me ask again someone from Rive team is this feasible for production or if not when it will be?

**Comment by BitBarrel** [comment]
You can try any Unity version and it should work. I just mentioned what works for me.

For official support yiu ahve to create a ticket at the Atlassian Rive site, not here.

https://rive.atlassian.net/servicedesk/customer/portals

**Comment by damzobridge** [comment]
Hi @pshtif 

The plugin is still in Technical Preview, so the APIs might change before the official release. However, I believe the issues you've mentioned have been fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188) upwards. Please let us know if you're still running into them.
