### ISSUE TITLE
Rive Assets are not rendered in a URP Unity Project

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#43]
Hi,

I tried recreating the "DrawToCube" scene in a Unity URP Project but I am not able to render the Rive asset on to the faces of the Cube. The Rive Unity Runtime I am using is of version v0.1.112

1. I created a Material with Lit Shader (I also tried with the Standard Shader)
![image](https://github.com/rive-app/rive-unity/assets/20733892/8e304f6c-cddc-4798-aad8-68e9dcbed43d)

2. I created a Render Texture and assigned it to the previously created Material
![image](https://github.com/rive-app/rive-unity/assets/20733892/bd77d523-5a32-43e1-9068-2634308f05db)

3. I attached the RiveTexture.cs script to the Cube and assigned it the relevant assets 
![image](https://github.com/rive-app/rive-unity/assets/20733892/101eb79c-ebc9-439e-a4bb-1d94d6f43cf6)

4. When I run the Scene, I don't see the Rive asset on the Cube
![image](https://github.com/rive-app/rive-unity/assets/20733892/d030a167-7bed-41ed-ac4f-b4b7663e118a)

Is it possible to render Rive Assets in a Unity URP Project?

Thank you.

**Comment by trdroid** [comment]
One observation I made is that in a non URP Project which successfully renders a Rive Asset, I see a Command Buffer attached to the Camera Component of the Main Camera Game Object BUT in a URP Project which DOES NOT render a Rive Asset, I DO NOT see any such Command Buffer attached to the Camera Component of the Main Camera Game Object.

The following shows the Camera Component in a Non URP Unity Project with a Command Buffer (and which renders a Rive asset)
![image](https://github.com/rive-app/rive-unity/assets/20733892/e1c46132-7796-4177-8d9c-b43880b16cb5)

The following shows the Camera Component in a URP Unity Project WITHOUT a Command Buffer (and which DOES NOT render a Rive Asset)
![image](https://github.com/rive-app/rive-unity/assets/20733892/f38165a0-c106-4955-8be0-944d63900728)

**Comment by BitBarrel** [comment]
URP is quirky. Try this:

-Download and use Unity version 2023.1.17f1
-Download and open the minion project (not the rotating cube) using the aforementioned Unity version. Minion project here: https://github.com/rive-app/rive-unity-examples
-Use Rive unity tag version 0.1.108

**Comment by pjarnfelt** [comment]
It is correct that the command buffer does not work in URP. Here it important to call m_riveRenderer.Submit(); 

 ```
private void Update()
    {
        m_riveRenderer.Submit();
        if (m_stateMachine != null)
        {
            m_stateMachine.Advance(Time.deltaTime);
        }
    }
```
as seen in the Minion Project's RiveTexture.cs
https://github.com/rive-app/rive-unity-examples/blob/main/minion-head-tracking-urp/Assets/Rive/RiveTexture.cs

**Comment by trdroid** [comment]
I tried your approach and now I am able to see the Rive asset rendered when I hit play in the Unity Editor; However, when I build the project to WebGL, the Rive Assets are NOT rendered, which I specified here: https://github.com/rive-app/rive-unity/issues/50
