### ISSUE TITLE
Rive Assets are not rendered when deployed to an Android device from Unity

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#44]
Hi,

I am trying to run the Scene "DrawToCube" on an Android Device but I do not see the Rive Asset being rendered. The Rive Unity Runtime version is v0.1.112

The scene renders the Rive Asset on a Cube when played in the Unity Editor
![image](https://github.com/rive-app/rive-unity/assets/20733892/eda1cb95-3dba-4a6f-aba0-acdc650bb86b)

But the same scene, when deployed to Android from Unity, DOES NOT render the Rive Asset
![image](https://github.com/rive-app/rive-unity/assets/20733892/b45e73d5-5dc2-4a2d-a8a4-b93136f1a24a)

**Comment by damzobridge** [comment]
Could you provide a bit more info about the Android device/environment you're testing on? Also, since that's the DrawToCube scene, I assume you're using the Built-In Render Pipeline not URP?

**Comment by trdroid** [comment]
Hi @damzobridge, as I am traveling I do not have access to my setup that I used to try this out, but I believe I used the Built-in Render Pipeline NOT the URP. I also recall using the default Android Build Settings in Unity 2022.3.10f and I deployed the build to a Samsung Edge S20+

**Comment by damzobridge** [comment]
This should be fixed from [v0.1.188](https://github.com/rive-app/rive-unity/releases/tag/v0.1.188)! Let us know if you still run into any issues with android not rendering Rive files.
