### ISSUE TITLE
Visual artifacts in editor

### ISSUE THREAD

**Issue by GariestGary** [rive-app/rive-unity#48]
![fBArH13JX3](https://github.com/rive-app/rive-unity/assets/38670681/9af71572-e155-4a0e-8186-0a1a1a1584ae)
![PkhzJ3JY8n](https://github.com/rive-app/rive-unity/assets/38670681/cb08b273-feaf-409f-8765-7ccea99cc58c)
![SThUTPeaz7](https://github.com/rive-app/rive-unity/assets/38670681/cefb64f1-499f-4464-a8f1-5459bbd64fa6)

package version 0.1.129
Editor version 2022.3.10f1

Hardware:
AMD Ryzen 5 4600G with Radeon Graphics   3.70 GHz
32 GB RAM
AMD Radeon RX 580 2048SP

Windows 10 22H2 x64

When switching from OpenGL to DirectX artifacts gone, but when clicking play button the editor crashes even without any notifications, just closes

**Comment by damzobridge** [comment]
Hello! Can you verify that this still happens on the latest version? We recently pushed a fix that might address this.
