### ISSUE TITLE
Building a Unity URP Project that uses a Rive Animation to WebGL Fails

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#49]
Hi,

I tried running the minions Unity Project in the Unity Editor and it's working fine, but when I tried to build the Unity Project to WebGL, it is failing with the following errors;

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
emcc: error: Library/PackageCache/app.rive.rive-unity@ba61818f2a/Runtime/Libraries/iOS/rive.a: Unknown format, not a static library!

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
emcc: error: Library/PackageCache/app.rive.rive-unity@ba61818f2a/Runtime/Libraries/iOS/rive.a: Unknown format, not a static library!

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

The snapshots are as follows:

![image](https://github.com/rive-app/rive-unity/assets/20733892/c5693440-f261-48ab-9b2b-57c445da112e)

![image](https://github.com/rive-app/rive-unity/assets/20733892/dffbcbf5-4a2c-4a84-b05d-d54328d09742)

Is there any work around?

Thank you

**Comment by trdroid** [comment]
Version of Rive-Unity runtime that I am using is v0.1.146

**Comment by damzobridge** [comment]
This build error has been fixed in `v1.169` upwards. Please try upgrading and let us know if this issue is still present. 

P.S. [The other issue](https://github.com/rive-app/rive-unity/issues/50) with URP not rendering properly, however, is still in progress.
