### ISSUE TITLE
Building a Unity URP project to WebGL DOES NOT render Rive Assets

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#50]
Hi,

I recreated the DrawToCube Scene in a Unity URP Project and I am able to see the Rive Asset when I hit play in the Unity Editor; See below:

![image](https://github.com/rive-app/rive-unity/assets/20733892/41ad8f6a-c9dd-4e7f-a5d7-3040b3d331c9)

But when I build the project to WebGL, the Rive Asset DOES NOT appear anymore, see below:

![image](https://github.com/rive-app/rive-unity/assets/20733892/89ed6adc-0ad8-4b82-8d6b-1a1c6fa2c2d0)

I was wondering if there is a workaround for this.

The version of Rive-Unity Runtime that I am using is v0.1.112

**Comment by chris-crucible** [comment]
I am seeing the same issue with latest version 0.1.146. Have you found any solution for this yet?

**Comment by chris-crucible** [comment]
I am having similar issues with WebGL using the latest Rive Unity version 0.1.146. I'm on Unity 2023.2.19f1. I am actually able to get the "DrawToCubeScene" in the getting-started samples to render somewhat correctly, though the lighting seems incorrect (see screenshot below). 

However, if I run the minion demo, the textures fail to render in the same way you show above, perhaps because of this error which I see in the console: `RenderTexture.Create failed: format unsupported for random writes - RGBA8 sRGB` 

I have attempted to patch Unity's version of Empscripten as recommended here: https://github.com/rive-app/rive-unity/blob/main/WEBGL.md But I'm not sure how to verify whether this is being picked up, or whether it's related to the problem. 

![Screenshot 2024-05-16 at 2 10 49 AM](https://github.com/rive-app/rive-unity/assets/52264903/7d6a6a9a-c68c-4df0-a919-0b920b3844f7)

**Comment by chris-crucible** [comment]
I just confirmed that the Emscripten patch is being picked up, but the `if` block provided in the readme is never getting entered. Is the issue that random writes should be disabled on WebGL, and this patch should be fixing the issue of the black screen? If so, is the suggested patch incorrect for more recent versions of Rive Unity?

**Comment by trdroid** [comment]
Hi @chris-crucible, I think that your DrawToCube Scene renders in WebGL because it is a Non-URP Unity Project. Since the minions example is a URP Unity Project, it DOES NOT render in WebGL, which is the reason why I specifically created this work item as Rive Assets in a Unity URP Project do not render in WebGL.

**Comment by damzobridge** [comment]
We're looking into this, it seems the WebGL build works with the built-in render pipeline, but not URP at the moment.

We recently pushed a version that removes the need to use the Emscripten patch for WebGL, so you shouldn't have to worry about that once we've fixed the URP issue.

**Comment by trdroid** [comment]
@chris-crucible, I share the same set of questions as you've mentioned. It did occur to me as to why we need two ways of rendering Rive Assets: the command buffer way for the built-in render pipeline Unity Projects and the Submit() way for the URP Unity Projects. Perhaps this has to do with the internals of Unity and Rive that is best suited for someone from the Rive team to answer.

**Comment by damzobridge** [comment]
Unfortunately, due to the way the render pipelines are set up, we have to use slightly different approaches to accommodate the discrepancies between them.

Thanks for the feedback! Ideally, we'd like to get to a point where you don't have to think about this at all when using the API.

**Comment by trdroid** [comment]
Hi @damzobridge, I was wondering if you have an update on this. It'd be great if you could specify a tentative timeline as to when this issue could be addressed so that I can decide if I should proceed with a Unity Project with a Standard Render Pipeline or with a URP.

**Comment by damzobridge** [comment]
Hi @trdroid , we're working on a larger update that will include high-level components that handle rendering across built-in RP, URP, and HDRP. However, for that, we'll be moving away from the `Submit()` approach and integrating a bit closer with the different SRP pipelines.

In the meantime, the updated [RiveTexture script here](https://github.com/rive-app/rive-unity-examples/blob/main/minion-head-tracking-urp/Assets/Rive/RiveTexture.cs) should address the black texture problem. Let me know if that isn't the case on your end!

**Comment by trdroid** [comment]
Hi, I tried drawing a Rive texture on a Cube in a URP Unity Project using the Rive-Unity version v0.1.195. It works within the Unity Editor BUT NOT when built to WebGL. In WebGL, I just see a dark screen as shown below:

![image](https://github.com/rive-app/rive-unity/assets/20733892/90128e78-2b73-4ab6-a1e4-e62ed9f98908)

This is the zipped Unity Project that I made:
[RiveURPWebGL.zip](https://github.com/user-attachments/files/16118453/RiveURPWebGL.zip)

**Comment by damzobridge** [comment]
Hi @trdroid , thanks for sending over the Unity project. It looks like you're still using the old version of the RiveTexture script in your project. I changed it to the new [RiveTexture script](https://github.com/rive-app/rive-unity-examples/blob/main/minion-head-tracking-urp/Assets/Rive/RiveTexture.cs) I mentioned earlier, and it builds and renders properly. Let me know if that fixes things for you!

<img width="990" alt="URPWebGLBuildTestSnapshot" src="https://github.com/rive-app/rive-unity/assets/67035612/4ae45de6-f637-45d2-901d-77f797a20cac">

Also, in terms of package versions, I recommend using the ones on the [releases](https://github.com/rive-app/rive-unity/releases) page as those are usually more stable.

**Comment by trdroid** [comment]
Hi @damzobridge, thank you so much! I have it working with the release version of Rive-Unity. I even have the script working with the click listener wherein I could interact with the stars on the Rive Texture. 

A follow up question:  

Apart from how we render Rive Textures in a Unity URP Project, are there differences in what features of Rive are supported across the Standard Render Pipeline and the URP? To elaborate a bit, are there features specific to Rive (let's say, state machines) that ONLY work in a Standard Pipeline but not in URP?

**Comment by damzobridge** [comment]
Glad to hear it's working for you @trdroid . Apart from slightly different rendering approaches, everything else works the same feature-wise across render pipelines!
