### ISSUE TITLE
v0.1.159 - "Object reference not set to an instance of an object" ERROR in your basic example

### ISSUE THREAD

**Issue by issimissimo** [rive-app/rive-unity#55]
Hello, I've just updated from v0.1.146 and the basic example "RiveTexture.cs" does not work anymore.
I get "Object reference not set to an instance of an object" at line 36  "m_artboard = m_file.Artboard(0);" with every Rive asset I've created.

**Comment by abethke** [comment]
Have you tried a fresh project? I was able to get the examples working in Unity 2022 and Unity 2023

**Comment by damzobridge** [comment]
Are you able to provide us with a repro project we can test on our end? 

I also recommend checking if the example projects have the same issue. That would help us narrow things down a bit.

**Comment by abethke** [comment]
The example projects do have the same issue. ~ABOn Jun 6, 2024, at 4:37 PM, Adam ***@***.***> wrote:﻿
Are you able to provide us with a repro project we can test on our end?
I also recommend checking if the example projects have the same issue. That would help us narrow things down a bit.
