### ISSUE TITLE
Logging not working in Editor

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#60]
When deploying a Unity build on an iPad, still connected to Xcode by cable, I get the following message in the Xcode console:

"state machine exceeded max iterations"

However, this message is not show in Unity. This makes debugging harder. Please find a way to show this message in Unity and also indicate from which state machine the issue arises.

**Comment by damzobridge** [comment]
Are you able to make a Mac dev build? If so, could you verify that the `state machine exceeded max iterations` message is logged in that build as well? That would help us rule out the possibility that the issue is only happening on certain target platforms (e.g iPad).

**Comment by BitBarrel** [comment]
I already fixed the issue. I emailed the dev team and they were able to tell me which state machine had the problem. It was cause by a race condition in a state machine which should happen at all platforms, but for some reason was only logged on IOS.
