### ISSUE TITLE
Colors in a Rive file appears washed out when rendered in a Unity URP project

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#62]
Hi,

I created a Rive file that appears like this:

![image](https://github.com/user-attachments/assets/b5bf9e4a-2ab0-4cf4-9c50-5f7633bd73c6)

When I render the Rive File in a Unity Built-in Render Pipeline Project, it appears as how it appears in the Rive Editor; A snapshot is shown below: 
![image](https://github.com/user-attachments/assets/617aba1c-3787-42fe-a852-0f910cbc2207)

BUT, when I render the same Rive File in a Unity URP Project, it appears washed out, as shown below:
![image](https://github.com/user-attachments/assets/4b0540ff-a0ff-4cb7-8bab-a9da08cd0422)

Any ideas as to how I can render the Rive file with accurate colors in a Unity URP Project?

The Rive Assets along with both the Unity Projects could be found in the attachment below, which contains the following:
RiveWithStandardUnity is the Unity Built-in Render Pipeline Project that renders a Rive file,
RiveWithUnityURP is the Unity URP Project that renders a rive file

[Files.zip](https://github.com/user-attachments/files/16281005/Files.zip)

Thank you.

**Comment by damzobridge** [comment]
Hi, 

It looks like your URP project is in Linear color space. The Rive Editor works in Gamma color space, so there will be differences when used in linear space in Unity. 

You'll need to switch the color space to Gamma in `Player Settings` if you want to keep the same look. If you want to stay in Linear space, then you would need to use post processing to get it closer to the Gamma look.

**Comment by Cosmas47** [comment]
I know this one is really old but this is a TREMENDOUS caveat on existing projects. Are there any other recommendations besides changing the projects color space?
