### ISSUE TITLE
File.Load(asset) fails on Unity

### ISSUE THREAD

**Issue by BitBarrel** [rive-app/rive-unity#64]
This line works well in the Editor on windows:
m_file = File.Load(asset);

But with an Android deployment, it returns zero.

I am also getting this error in the console:
[Worker0] OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Any ideas?

**Comment by damzobridge** [comment]
For the file loading issue, can you confirm that you're using the OpenGL Graphics APIs and not Vulkan? I'm not able to reproduce this on my end on Android.

The `OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM` error is a known issue, and we're looking into it.

**Comment by BitBarrel** [comment]
Indeed it was caused by Vulkan being set by the automatic graphics API setting.

I have two recommendations to make related to this:

1. In the example projects (basic and other Unity example projects), do not set the graphics API to automatic but instead to manual with no Vulkan selected.
2.  Detect if Vulkan is used and throw an understandable error instead of quietly not working on Android.
