### ISSUE TITLE
Publish to IOS with rive 0.1.273 will encounter 2 errors

### ISSUE THREAD

**Issue by polaris7765** [rive-app/rive-unity#68]
`In /Users/admin/Workspace/OnlineClassApp/onlineclassapp/ios/Libraries/ThirdParty/rive-unity-0.1.273/package/Runtime/Libraries/iOS/rive.a(plugin.o), could not parse object file /Users/admin/Workspace/OnlineClassApp/onlineclassapp/ios/Libraries/ThirdParty/rive-unity-0.1.273/package/Runtime/Libraries/iOS/rive.a(plugin.o): 'Invalid bitcode version (Producer: '1500.3.9.4.0_0' Reader: '1403.0.22.14.1_0')', using libLTO version 'LLVM version 14.0.3, (clang-1403.0.22.14.1)' for architecture arm64  `

![image](https://github.com/user-attachments/assets/bd4873ab-b017-4a3e-b0b3-3a0d7425f2c0)

**Comment by damzobridge** [comment]
Can you try again with [v276](https://github.com/rive-app/rive-unity.git?path=package#v0.1.276) and let us know if that fixes things? If possible, please restart the Unity editor after you've updated the package.

**Comment by polaris7765** [comment]
thanks for you help, v276 also have this problem.

In /Users/admin/Workspace/OnlineClassApp/onlineclassapp/ios/Libraries/ThirdParty/rive-unity-0.1.276/package/Runtime/Libraries/iOS/rive.a(plugin.o), could not parse object file /Users/admin/Workspace/OnlineClassApp/onlineclassapp/ios/Libraries/ThirdParty/rive-unity-0.1.276/package/Runtime/Libraries/iOS/rive.a(plugin.o): 'Invalid bitcode version (Producer: '1500.3.9.4.0_0' Reader: '1403.0.22.14.1_0')', using libLTO version 'LLVM version 14.0.3, (clang-1403.0.22.14.1)' for architecture arm64

![image](https://github.com/user-attachments/assets/20662795-d1e3-44ae-8692-e419f6e90908)

**Comment by damzobridge** [comment]
Very strange. Could you provide more info about the target device (which version of iOS you're building for) and other build settings ? I'm not currently able to reproduce this issue on iPhone 11 and iOS 17.5.1.

**Comment by polaris7765** [comment]
maybe the problem is my xcode version is to old, i'll try to upgrade to latest and try again.

**Comment by polaris7765** [comment]
it's works after i upgrade macOs to 14.6.1 and xcode to 15.4.
thank you.

**Comment by damzobridge** [comment]
Thanks for letting us know! Glad it works now.
