### ISSUE TITLE
Animating the size of an artboard does not render properly

### ISSUE THREAD

**Issue by trdroid** [rive-app/rive-unity#69]
Hi,

I have a Rive Asset that animates the position of a shape in an Artboard while also increasing the size of the Artboard. When I render this asset to the screen in Unity, the shape disappears few moments into the Animation. I tried all the Fit options but nothing seems to work. 

Attached to this work item are:

The Rive Asset
[animatingartboardsize.zip](https://github.com/user-attachments/files/16898567/animatingartboardsize.zip)

The Unity Project (please look at the DrawToCameraScene)
[getting-started.zip](https://github.com/user-attachments/files/16898553/getting-started.zip)

**Comment by trdroid** [comment]
I guess I should probably keep the size of the artboard constant and play with the size of its content. 

If I have content that spans, let's say, four times the size of an Artboard, how can I deal with scrolling along the width of the Artboard?

**Comment by damzobridge** [comment]
Changing an artboard's size at runtime is not supported at the moment. With our upcoming layout feature, you'll be able to achieve what you're trying to do completely in Rive.

In the meantime, if you're using Rive with Canvas, you can use a regular scroll view element to hold the Rive visual and have the Rive content set to the expected full size of the artboard.
