### ISSUE TITLE
Editor crashes when import .riv file to unity

### ISSUE THREAD

**Issue by polaris7765** [rive-app/rive-unity#70]
Unity : 2024.3.42f1c1
MacOs: 1015.7
publish for platform : Android
when download project from git, it will see the importer issues.
when you reimport, the unity IDE will crash immediately. 
https://github.com/user-attachments/assets/f49a8e5f-6ef9-4378-85ad-1704359c240a

**Comment by polaris7765** [comment]
Rive version: 0.1.276

**Comment by damzobridge** [comment]
Does this happen when you install Rive into a fresh project or just when you upgrade the Rive plugin to a newer version in an existing project?

**Comment by polaris7765** [comment]
It happen after upgrade the Rive plugin to a newer version.

**Comment by damzobridge** [comment]
Thanks for responding. In that case, the crash is related to this [issue](https://github.com/rive-app/rive-unity/issues/59#issuecomment-2256673966). It's something we're working on addressing in some form within the Unity Editor.
