### ISSUE TITLE
Flickering issue on Android OpenGLES3

### ISSUE THREAD

**Issue by jleblancsw** [rive-app/rive-unity#80]
Hello,
We seem to keep having flickering issues with some of our Rive files. It happens for some of the shapes.
It seems to be related to gradients? Not exactly sure what's going on...

**Unity Version:** 2022.3.20f1 **(Also happens on 2022.3.10f1 with Rive Example Project)**
**Rendering Pipeline:** Built-In Render Pipeline
**Graphics API:** OpenGLES3
**Platform:** Android
**Rive Package:** https://github.com/rive-app/rive-unity.git?path=package#v0.2.1
**Scripting Backend:** IL2CPP
**Target Architecture:** ARM64

![Joey3](https://github.com/user-attachments/assets/632329d1-dc5d-4e40-8dde-270684a294c5)

I can share a .rev file with the problem if I can work with someone from the team directly.
Let me know if I'm missing any details that could help.

Thank you!
-Jesse

**Comment by jleblancsw** [comment]
I forgot to add it seems to only happen on some Android devices.
Pixel 6 and up in particular.

I'm using a Pixel 9 in this example.

**Comment by csmartdalton** [comment]
Hi Jesse. Thanks for sharing your issue! I would love to take a look at that file and see if I can repro/fix on my end. Can you reach out to me at chris@rive.app ?

**Comment by jleblancsw** [comment]
Thanks Chris, I reached out.
