### ISSUE TITLE
The state machines does not work in this version.

### ISSUE THREAD

**Issue by polaris7765** [rive-app/rive-unity#81]
"rive version": "0.3.1-canary.26"
"unity version:" "2022.3.49f1c1"

`private void SetValue(string numberName, int num)
        {
            var mStateMachine = m_rive_file.Artboard.StateMachine(0);
            var input = mStateMachine.GetNumber(numberName);
            input.Value = num;
  }

private void Update()
{
    if (m_stateMachine != null)
    {
        m_stateMachine.Advance(Time.deltaTime);
    }
}
`
i see input value was set correctly, but the rive state was not change.

**Comment by damzobridge** [comment]
Hi, does this also happen with the [v0.2.1](https://github.com/rive-app/rive-unity/releases/tag/v0.2.1) release?

**Comment by polaris7765** [comment]
i used urp pipeline, it's looks like v0.2.1 does not support urp?

**Comment by polaris7765** [comment]
Because v0.3.1 have Rive Panel and Rive Widget, we can easily add rive animation to UGUI.
but we also find the rive rendered will extra add a black outline.
![image](https://github.com/user-attachments/assets/cf09dfa3-199c-4014-921a-91425a52135a)

**Comment by damzobridge** [comment]
Ohh I see! When using the RivePanel and RiveWidget, you no longer need to call `advance()` or instantiate the statemachine yourself like you're doing with `m_rive_file.Artboard.StateMachine(0);`

In your script, you can take a reference to the rive widget:

```
        [SerializeField] private RiveWidget m_riveWidget;
        
        void Start()
        {
        
             if (m_riveWidget.Status == WidgetStatus.Loaded)
            {
               var input = m_riveWidget.StateMachine.GetNumber(numberName);
               input.Value = num;
            }
        }
   

```

In your current script, you're creating a new state machine rather than using the reference in the widget, so you won't be able to see any changes because they're being applied to a different statemachine.

**Comment by damzobridge** [comment]
Are you able to share the `.riv`/`rev` file with us so we can take a look at the outline issue?

If you don't want to share it publicly, you can also send it to us privately [here](https://rive.atlassian.net/servicedesk/customer/portals).

**Comment by polaris7765** [comment]
> Are you able to share the `.riv`/`rev` file with us so we can take a look at the outline issue?
> 
> If you don't want to share it publicly, you can also send it to us privately [here](https://rive.atlassian.net/servicedesk/customer/portals).

I had send You a .riv file by the privately link (RIV-7607).
please check this problem,  thanks for your help.

At the beginning i want use a shader to fix this problem as before, but in this version it' not easy to apply that.

**Comment by polaris7765** [comment]
> > so, where can i see the up to date API document?
> 
> This will be available [here](https://rive.app/community/doc/getting-started/docQycIiNOv4) later this week
> 
> Regarding the outline issue, is this what you're referring to (the dark lines around the finger edges):
> 
> <img alt="Screenshot 2024-12-17 at 9 14 21 AM" width="328" src="https://private-user-images.githubusercontent.com/67035612/396597738-cee0db08-32cc-4b65-9c76-68a74388dccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODExNDEsIm5iZiI6MTczNDQ4MDg0MSwicGF0aCI6Ii82NzAzNTYxMi8zOTY1OTc3MzgtY2VlMGRiMDgtMzJjYy00YjY1LTljNzYtNjhhNzQzODhkY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAwMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTk1OGVjODYzMDUzMDgyZTk5ODRhY2FhMmRjN2Y5ZjFiNGIxMTY3YTNjOGM2ZDEyODczZmIxYmE4YzhmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wknDGVZJORoqrB2InDLAdb3n42C1AVZIalutSSb3qdg">

yes,how can i solve this problem like this?

**Comment by damzobridge** [comment]
It's a renderering issue, so I'll bring it up with the team.

Before RivePanel and RiveWidget, were you applying a shader to a RawImage to fix it?

**Comment by polaris7765** [comment]
Yes, i found a solution to fix this problem. 
![image](https://github.com/user-attachments/assets/56784649-6e91-436d-80ef-65fcf7d998da)
also is change the raw Image shader, it's a Legacy shader can works in urp and build in.
![image](https://github.com/user-attachments/assets/b31c8b91-444c-4a9e-b459-06c7d3c3f13e)
