### ISSUE TITLE
Xcode build failed[Xcode Version 15.4 (15F31d)]

### ISSUE THREAD

**Issue by polaris7765** [rive-app/rive-unity#82]
Multiple errors: could not parse bitcode object file /Users/admin/Downloads/rive-unity-main/examples/ios/Libraries/app.rive.rive-unity/Runtime/Libraries/iOS/rive.a[730](unity_no_op_factory.o): 'Invalid bitcode version (Producer: '1600.0.26.4.0_0' Reader: '1500.3.9.4_0')', using libLTO version 'LLVM version 15.0.0' in '/Users/admin/Downloads/rive-unity-main 3/examples/ios/Libraries/app.rive.rive-unity/Runtime/Libraries/iOS/rive.a[730](unity_no_op_factory.o)';

**Comment by damzobridge** [comment]
This might be related to your [Xcode version](https://github.com/rive-app/rive-unity/issues/68). Are you able to update and try again?

**Comment by polaris7765** [comment]
Update Xcode to 16.2 can fix this problem.
Thanks for your help
